version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: exercise_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/exercise_tracker
      SECRET_KEY: super-secret-key-change-in-production-12345
    depends_on:
      - db

volumes:
  pgdata:
